### ISSUE TITLE
Example Program problems

### ISSUE THREAD

**Issue by Kroltez** [futomi/node-thunderboard-react#2]
I tried using your first example:

```
// Create a ThunderboardReact object
var ThunderboardReact = require('node-thunderboard-react');
var thunder = new ThunderboardReact();

// Initialize the ThunderboardReact object
thunder.init((error) => {
  // Discover the Thunderboard React Board Kit
  thunder.startDiscovery((device) => {
    console.log('- Found ' + device.localName);
    // Stop the discovery process
    thunder.stopDiscovery();
    // Connect to the found device
    device.connect((error) => {
      console.log('- Connected ' + device.localName);
      // Get the sensored data
      getEnvironmentalSensing(device);
    });
  });
});

// Get the sensored data
function getEnvironmentalSensing(device) {
  device.getEnvironmentalSensing((error, res) => {
    // Show the data
    console.log('- Sensored data:');
    console.log('  - Humidity    : ' + res.humidity + ' %');
    console.log('  - Temperature : ' + res.temperature + ' °C');
    console.log('  - UV Index    : ' + res.uvIndex);
    // Disconnect the device
    device.disconnect(() => {
      console.log('- Disconnected ' + device.localName);
      process.exit();
    });
  });
}
```
I saved it as ExampleA.js and run it as bellow and got this error:

```
pi@raspberrypi:~/code/ThunderBoard $ node ExampleA.js
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

**Comment by Kroltez** [comment]
updated blueZ with wget has solved that error. 
I get:
-Found Thunder React #15646 

Then nothing.
What is the program waiting for?

**Comment by Kroltez** [comment]
never mind that randomly worked this time.

Getting error on orientation program now though

**Comment by Kroltez** [comment]
pi@raspberrypi:~/code/ThunderBoard $ sudo node ExampleB.js
- Found Thunder React #15646
- Connected Thunder React #15646
- Orientation:
  - alpha :0°
  - beta  :-0.34°
  - gamma :0.03°
- Orientation:
  - alpha :-0.03°
  - beta  :-0.74°
  - gamma :0.05°
- Orientation:
  - alpha :-0.06°
  - beta  :-1.14°
  - gamma :0.08°
- Orientation:
  - alpha :-0.1°
  - beta  :-1.54°
  - gamma :0.11°
- Orientation:
  - alpha :-0.13°
  - beta  :-1.93°
  - gamma :0.14°
- Orientation:
  - alpha :-0.16°
  - beta  :-2.33°
  - gamma :0.17°
- Orientation:
  - alpha :-0.2°
  - beta  :-2.72°
  - gamma :0.19°
- Orientation:
  - alpha :-0.23°
  - beta  :-3.13°
  - gamma :0.21°
- Orientation:
  - alpha :-0.26°
  - beta  :-3.52°
  - gamma :0.24°
- Orientation:
  - alpha :-0.3°
  - beta  :-3.92°
  - gamma :0.27°
- Orientation:
  - alpha :-0.33°
  - beta  :-4.32°
  - gamma :0.3°
noble warning: unknown peripheral 000b570c3d1e
